--------------------------------------------------------------------------------
-- Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____
--  /   /\/   /
-- /___/  \  /    Vendor: Xilinx
-- \   \   \/     Version : 13.1
--  \   \         Application : xaw2vhdl
--  /   /         Filename : clock.vhd
-- /___/   /\     Timestamp : 02/27/2012 13:36:57
-- \   \  /  \
--  \___\/\___\
--
--Command: xaw2vhdl-st C:\Mathias\smole\etherlab\xilinx\ipcore_dir\.\clock.xaw C:\Mathias\smole\etherlab\xilinx\ipcore_dir\.\clock
--Design Name: clock
--Device: xc3s500e-4fg320
--
-- Module clock
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
LIBRARY UNISIM;
USE UNISIM.Vcomponents.ALL;

ENTITY clock IS
  PORT (
    CLKIN_IN : IN STD_LOGIC;
    RST_IN : IN STD_LOGIC;
    CLKIN_IBUFG_OUT : OUT STD_LOGIC;
    CLK0_OUT : OUT STD_LOGIC;
    CLK90_OUT : OUT STD_LOGIC);
END clock;

ARCHITECTURE BEHAVIORAL OF clock IS
  SIGNAL CLKFB_IN : STD_LOGIC;
  SIGNAL CLKIN_IBUFG : STD_LOGIC;
  SIGNAL CLK0_BUF : STD_LOGIC;
  SIGNAL CLK90_BUF : STD_LOGIC;
  SIGNAL GND_BIT : STD_LOGIC;
BEGIN
  GND_BIT <= '0';
  CLKIN_IBUFG_OUT <= CLKIN_IBUFG;
  CLK0_OUT <= CLKFB_IN;
  CLKIN_IBUFG_INST : IBUFG
  PORT MAP(
    I => CLKIN_IN,
    O => CLKIN_IBUFG);

  CLK0_BUFG_INST : BUFG
  PORT MAP(
    I => CLK0_BUF,
    O => CLKFB_IN);

  CLK90_BUFG_INST : BUFG
  PORT MAP(
    I => CLK90_BUF,
    O => CLK90_OUT);

  DCM_SP_INST : DCM_SP
  GENERIC MAP(
    CLK_FEEDBACK => "1X",
    CLKDV_DIVIDE => 2.0,
    CLKFX_DIVIDE => 1,
    CLKFX_MULTIPLY => 4,
    CLKIN_DIVIDE_BY_2 => FALSE,
    CLKIN_PERIOD => 20.000,
    CLKOUT_PHASE_SHIFT => "NONE",
    DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
    DFS_FREQUENCY_MODE => "LOW",
    DLL_FREQUENCY_MODE => "LOW",
    DUTY_CYCLE_CORRECTION => TRUE,
    FACTORY_JF => x"C080",
    PHASE_SHIFT => 0,
    STARTUP_WAIT => FALSE)
  PORT MAP(
    CLKFB => CLKFB_IN,
    CLKIN => CLKIN_IBUFG,
    DSSEN => GND_BIT,
    PSCLK => GND_BIT,
    PSEN => GND_BIT,
    PSINCDEC => GND_BIT,
    RST => RST_IN,
    CLKDV => OPEN,
    CLKFX => OPEN,
    CLKFX180 => OPEN,
    CLK0 => CLK0_BUF,
    CLK2X => OPEN,
    CLK2X180 => OPEN,
    CLK90 => CLK90_BUF,
    CLK180 => OPEN,
    CLK270 => OPEN,
    LOCKED => OPEN,
    PSDONE => OPEN,
    STATUS => OPEN);

END BEHAVIORAL;